library('dplyr')
chicago<-readRDS('chicago.RDS')
head(chicago)
str(chicago)
names(chicago)
head(select(chicago, city:dptp))
head(select(chicago, -(pm25tmean2:no2tmean2)))
chic.f<-filter(chicago,pm25tmean2>25)
head(chic.f)
chicago<-rename(chicago,pm2.5 = pm25tmean2)
names(chicago)
chicago<-mutate(chicago,pm25detrend = pm25-mean(pm25,na.rm = T))
chicago<-mutate(chicago, pm25detrend = pm2.5-mean(pm2.5,na.rm = T))
chicago<-arrange(chicago,date)
chicago<-arrange(chicago,desc(date))
head(chicago)
chicago<-rename(chicago,pm2.5 = pm25tmean2)
chicago<-mutate(chicago, pm25detrend = pm2.5-mean(pm2.5,na.rm = T))
head(chicago)
head(select(chicago,pm2.5,pm25detrend))
chicago<-mutate(chicago, tempcat = factor(1*(tmpd>80),labels = c('cold','true')))
chicago<-mutate(chicago, tempcat = factor(1*(tmpd>80),labels = c('cold','hot')))
head(filter(chicago, tempcat == 'hot'))
hotcold<-group_by(chicago,tempcat)
summarise(hotcold, pm2.5 = mean(pm2.5,rm.na =T), ozone = max(o3tmean2), no2 = median(no2tmean2))
summarise(hotcold, pm2.5 = mean(pm2.5,na.rm =T), ozone = max(o3tmean2), no2 = median(no2tmean2))
chicago<-mutate(chicago, year = as.POSIXlt(date)$year + 1900)
years<-group_by(chicago.year)
years<-group_by(chicago, year)
summarise(years, pm2.5 = mean(pm2.5,na.rm =T), ozone = max(o3tmean2), no2 = median(no2tmean2))
